.TH "GamePlayer" 3 "30 Apr 2009" "Version v0.0.1 Pre-Alpha" "Platform 2D Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GamePlayer \- The player character entity.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <GamePlayer.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGamePlayer\fP ()"
.br
.ti -1c
.RI "\fB~GamePlayer\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP (const char *image=NULL)"
.br
.ti -1c
.RI "void \fBDraw\fP (SDL_Surface *mainScreen)"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBSetMoveLeft\fP (const bool &flag)"
.br
.ti -1c
.RI "void \fBSetMoveRight\fP (const bool &flag)"
.br
.ti -1c
.RI "void \fBSetMoveUp\fP (const bool &flag)"
.br
.ti -1c
.RI "void \fBSetMoveDown\fP (const bool &flag)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The player character entity. 

\fBGamePlayer\fP is an entity representing the avatar of the human player on the screen. It is usually the center focus of the player's attention and the proxy through which the player expects to operate. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GamePlayer::GamePlayer ()"
.PP
.SS "GamePlayer::~GamePlayer ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void GamePlayer::Draw (SDL_Surface * mainScreen)"
.PP
Draws the image of the player to the indicated surface, usually the primary display screen of the engine. This function is dependent upon the existance of both the player image and the screen.
.PP
\fBParameters:\fP
.RS 4
\fImainScreen\fP The surface that the image is to be drawn to 
.RE
.PP

.SS "void GamePlayer::Init (const char * image = \fCNULL\fP)"
.PP
Initiates the player object by loading the relevant image and dimension information.
.PP
\fBParameters:\fP
.RS 4
\fIimage\fP The full path to the file to be used as the player image 
.RE
.PP

.SS "void GamePlayer::SetMoveDown (const bool & flag)"
.PP
.SS "void GamePlayer::SetMoveLeft (const bool & flag)"
.PP
.SS "void GamePlayer::SetMoveRight (const bool & flag)"
.PP
.SS "void GamePlayer::SetMoveUp (const bool & flag)"
.PP
Moves the player by changing its position on the 2D grid, using the dimensions passed in the delta as modifiers.
.PP
\fBParameters:\fP
.RS 4
\fIdelta\fP The 2D movement vectors of the player 
.RE
.PP

.SS "void GamePlayer::Update ()"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Platform 2D Game Engine from the source code.
