.TH "GamePlayer" 3 "22 Apr 2009" "Version v0.0.1 Pre-Alpha" "Platform 2D Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GamePlayer \- The player character entity.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <GamePlayer.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGamePlayer\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBDrawPlayer\fP (\fBPlatformEngine\fP *game)"
.br
.ti -1c
.RI "void \fBMovePlayer\fP (SDL_Rect &delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The player character entity. 

\fBGamePlayer\fP is an entity representing the avatar of the human player on the screen. It is usually the center focus of the player's attention and the proxy through which the player expects to operate. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GamePlayer::GamePlayer ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void GamePlayer::DrawPlayer (\fBPlatformEngine\fP * game)"
.PP
.SS "void GamePlayer::Init ()"
.PP
.SS "void GamePlayer::MovePlayer (SDL_Rect & delta)"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Platform 2D Game Engine from the source code.
