.TH "GameMap" 3 "1 May 2009" "Version v0.0.1 Pre-Alpha" "Platform 2D Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameMap \- The map being used by the navigation state.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <GameMap.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameMap\fP ()"
.br
.ti -1c
.RI "void \fBMoveMap\fP (SDL_Rect &delta)"
.br
.ti -1c
.RI "void \fBDraw\fP (SDL_Surface *mainScreen)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The map being used by the navigation state. 

This is a 'map', or a 'world', that can be navigated and interacted with in the game navigation state. It consists of a stack of layers, which have a number of different types that can be used for different purposes. The map contains functions that specify where on the screen grid the layers it contains should be drawn, which is how it is told by the GameNavigationState which direction it should move in order to give the impression that the Player is moving about in the map. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameMap::GameMap ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void GameMap::Draw (SDL_Surface * mainScreen)"
.PP
Draws the map to the screen by drawing each of its layers to the screen, from 'bottom' to 'top', in sequence.
.PP
\fBParameters:\fP
.RS 4
\fImainScreen\fP The surface that the map is to be drawn to. 
.RE
.PP

.SS "void GameMap::MoveMap (SDL_Rect & delta)"
.PP
Moves the apparent position of the map on the screen, using the dimensions in the delta as modifiers of the map's original positioning.
.PP
\fBParameters:\fP
.RS 4
\fIdelta\fP The 2D movement vectors of the map on screen 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Platform 2D Game Engine from the source code.
