.TH "GameMap" 3 "30 Mar 2009" "Version v0.0.1 Pre-Alpha" "Platform 2D Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameMap \- A map used by the engine for navigation.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <GameMap.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameMap\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A map used by the engine for navigation. 

While the state 'GameNavigationState' is reponsible for engine operations while in that state, it makes use of this separate map class for functions pertaining to specifically moving the map in relation to the active player. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameMap::GameMap ()"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Platform 2D Game Engine from the source code.
