.TH "GameMapLayer" 3 "1 May 2009" "Version v0.0.1 Pre-Alpha" "Platform 2D Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameMapLayer \- A section of the map object.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <GameMapLayer.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameMapLayer\fP ()"
.br
.ti -1c
.RI "virtual void \fBDraw\fP (SDL_Surface *mainScreen)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
A section of the map object. 

This is an abstract class representing a layer of the map object used by the Navigation State. It is not meant to be used, but is the ancestor of several specific types of map layers. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameMapLayer::GameMapLayer ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "virtual void GameMapLayer::Draw (SDL_Surface * mainScreen)\fC [pure virtual]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Platform 2D Game Engine from the source code.
