.TH "Platform::GameMapBackgroundLayer" 3 "4 May 2009" "Version v0.0.1 Pre-Alpha" "Platform 2D Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Platform::GameMapBackgroundLayer \- 
.SH SYNOPSIS
.br
.PP
\fC#include <platform-game-map-layer-background.h>\fP
.PP
Inherits \fBPlatform::GameMapLayer\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameMapBackgroundLayer\fP ()"
.br
.ti -1c
.RI "\fB~GameMapBackgroundLayer\fP ()"
.br
.ti -1c
.RI "virtual void \fBInit\fP (SDL_Surface *theDisplay=NULL, char *imagePath=NULL, bool verticalScrolling=false)"
.br
.ti -1c
.RI "virtual void \fBDraw\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Platform::GameMapBackgroundLayer::GameMapBackgroundLayer ()"
.PP
.SS "Platform::GameMapBackgroundLayer::~GameMapBackgroundLayer ()"
.PP
.SH "Member Function Documentation"
.PP 
.SS "void Platform::GameMapBackgroundLayer::Draw ()\fC [virtual]\fP"
.PP
Implements \fBPlatform::GameMapLayer\fP.
.SS "void Platform::GameMapBackgroundLayer::Init (SDL_Surface * theDisplay = \fCNULL\fP, char * imagePath = \fCNULL\fP, bool verticalScrolling = \fCfalse\fP)\fC [virtual]\fP"
.PP
Implements \fBPlatform::GameMapLayer\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform 2D Game Engine from the source code.
