.TH "Platform::GameMapLayer" 3 "4 May 2009" "Version v0.0.1 Pre-Alpha" "Platform 2D Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Platform::GameMapLayer \- A section of the map object.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <platform-game-map-layer.h>\fP
.PP
Inherited by \fBPlatform::GameMapBackgroundLayer\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBInit\fP (SDL_Surface *theDisplay=NULL, char *imagePath=NULL, bool verticalScrolling=false)=0"
.br
.ti -1c
.RI "virtual void \fBDraw\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
A section of the map object. 

This is an abstract class representing a layer of the map object used by the Navigation State. It is not meant to be used, but is the ancestor of several specific types of map layers. 
.SH "Member Function Documentation"
.PP 
.SS "virtual void Platform::GameMapLayer::Draw ()\fC [pure virtual]\fP"
.PP
Implemented in \fBPlatform::GameMapBackgroundLayer\fP.
.SS "virtual void Platform::GameMapLayer::Init (SDL_Surface * theDisplay = \fCNULL\fP, char * imagePath = \fCNULL\fP, bool verticalScrolling = \fCfalse\fP)\fC [pure virtual]\fP"
.PP
Implemented in \fBPlatform::GameMapBackgroundLayer\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Platform 2D Game Engine from the source code.
